[[redirects]]
  from = "/"
  to = "/src/html/TN-1_HomePage.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"